version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - ./.data:/var/opt/mssql/data
      - ./archivos:/var/opt/mssql/archivos
    environment:
      SA_PASSWORD: "MyP@55w0rd"
      ACCEPT_EULA: "Y"
#docker run --name=OracleXE --shm-size=1g -p 1521:1521 -p 8080:8080 -e ORACLE_PWD=MyP@55w0rd -v db-data-oracle:/opt/oracle/oradata thebookpeople/oracle-xe-11g
  db-mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=MyP@55w0rd
    ports:
      - "3306:3306"
    volumes:
      - ./db-data-mysql:/var/lib/mysql