version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - ./.data:/var/opt/mssql/data
      - ./archivos:/var/opt/mssql/archivos
    environment:
      SA_PASSWORD: "MyP@55w0rd"
      ACCEPT_EULA: "Y"
  db-oracle:
    image: thebookpeople/oracle-xe-11g
    restart: always
    environment:
      - ORACLE_ALLOW_REMOTE=true
#      - ORACLE_ALLOW_REMOTE=true
#      - ORACLE_DISABLE_ASYNCH_IO=true
#      - ORACLE_PASSWORD=MyP@55w0rd
    ports:
      - "1521:1521"
    volumes:
      - ./db-data-oracle:/u01/app/oracle
  db-mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=MyP@55w0rd
    ports:
      - "3306:3306"
    volumes:
      - ./db-data-mysql:/var/lib/mysql